### ISSUE TITLE
Only nucleus being segmented under mesmer 

### ISSUE THREAD

**Issue by pushkal777** [vanvalenlab/kiosk-imageJ-plugin#38]
I uploaded a 2-channel stack with DAPI/YFP. After submitting it, I get small segmented regions marking only the nucleus. Not sure what is going wrong. 
Result window from mesmer plugin:
![3](https://user-images.githubusercontent.com/24880707/110493869-05d7bc00-80c1-11eb-8fee-c13defe4db97.GIF)

Input stacked image (contains these two images):
![1](https://user-images.githubusercontent.com/24880707/110493872-0708e900-80c1-11eb-816e-2914877a61db.GIF)
![2](https://user-images.githubusercontent.com/24880707/110493878-083a1600-80c1-11eb-8367-5462e8c52ede.GIF)

**Comment by willgraf** [comment]
Thanks for the issue. The root cause is that the zip file produced contains 2 tiff images for Nuclear and Cytoplasm segmentation. However, the `ij.io.Opener.openURL` method only opens a single file from the zip. I had thought it was opening the whole-cell image but this is definitely nuclear.

I'll bump this up the priority list, but in the meantime, you can download both segmentation images from [deepcell.org](https://deepcell.org/predict).

**Comment by ngreenwald** [comment]
I think this is an issue with cell culture data. Our model was trained only on tissue data, and isn't designed for cell culture. 
I'm able to get whole-cell segmentation results when running our default image
![image](https://user-images.githubusercontent.com/13770365/110517327-92817a80-80bf-11eb-8f3e-d1274adcf295.png)

**Comment by pushkal777** [comment]
Thanks for getting back. What differences do you think are in a cell culture vs 2D tissue culture images for the algorithm? Also, do you have other suggestions on other trained models for cell culture segmentation?

**Comment by ngreenwald** [comment]
The membrane signal for cell culture looks quite different than in tissue samples, which is why Mesmer is defaulting to just nuclear segmentation for your data. I'd recommend checking out CellPose for cell culture segmentation
