### ISSUE TITLE
Only one output when running mesmer on imageJ

### ISSUE THREAD

**Issue by yokotenka** [vanvalenlab/kiosk-imageJ-plugin#43]
Hello DeepCell team,

First of all, thank you for creating this amazing tool.

I have a naive question. I am currently trying to get the whole cell and nuclei segmentation using the Mesmer method on ImageJ. I have followed the given instructions with the sample image on deepcell.org/predict and the plugin itself runs fine. However, I am only getting the whole cell segmentation result returned ( a mask image labelled {image_name}_feature_0.tif). When I run the prediction on the deepcell.org website with the same image, and when I download the results, I get both of the mask images. 

Is there an option that I am missing which allows me to get both of the results? 

Thank you for the help in advance.

**Comment by ngreenwald** [comment]
Yes, due to some limitations with how images are passed between the different platforms, we didn't find an easy way to allow both segmentation predictions to be generated, so we defaulted to showing the whole-cell predictions. If you'd like to generate both sets of predictions for your images, you'll need to either use the website or a local installation.
